bbs/urls.py
from django.urls import path
from bbs import views
from chat.views import user_info
from notif.views import leave_message


app_name = 'bbs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 板块页面
    path('plate=<int:plate_id>&page=<int:page>', views.plate, name='plate'),
    # 帖子详情页
    path('article=<int:article_id>&page=<int:page>', views.article, name='article'),
    # 发表帖子页面
    path('plate=<int:plate_id>/post', views.post, name='post'),
    # 发表回复页面
    path('article=<int:article_id>/reply', views.reply, name='reply'),
    # 用户发帖记录页面
    path('user/my_article', views.my_article, name='my_article'),
    # 用户回复记录页面
    path('user/my_comment', views.my_comment, name='my_comment'),
    # 编辑帖子页面
    path('article=<int:article_id>/edit', views.edit_article, name='edit_article'),
    # 编辑回复
    path('comment=<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    # 删除帖子页面
    path('article=<int:article_id>/delete', views.delete_article, name='delete_article'),
    # 删除回复页面
    path('comment=<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    # 查询页面
    path('search/', views.search, name='search'),
    # 开发者邮箱
    path('mailbox/',views.mailbox,name = 'mailbox'),
    # 留言页面
    path('user_info/<str:username>', user_info, name='user_info'),
    # 留言板展示
    path('mailboard/',views.mailshow,name = 'mailshow'),
    # 留言页面
    path('notif/leave_message/<str:receiver_username>', leave_message, name='leavemes'),
]

bbs_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('bbs.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('notif/', include('notif.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notif/urls.py
from django.urls import path, include
from notif import views
from django.urls import re_path

app_name = 'notif'
urlpatterns = [
    path('notifview/<int:notif_id>/', views.notification_view, name='notifview'),
    path('notif/', views.notification_list, name='notiflist'),
    path('notifrm/<int:notif_id>/', views.remove_notification, name='notifrm'),
    path('mark_all_read/', views.mark_all_read, name='notifmar'),
    path('delete_all_read/', views.delete_all_read, name='notifdar'),
    path('user_notifications_count/', views.user_notifications_count, name='notifcount'),
    path('leave_message/', views.leave_message, name='leavemes'),
]

notif/models.py
import logging

from django.db import models
from django.conf import settings

logger = logging.getLogger(__name__)
class Notification(models.Model):
    """Notification to a user within Auth"""

    NOTIFICATIONS_MAX_PER_USER_DEFAULT = 100#最大通知数量
    NOTIFICATIONS_REFRESH_TIME_DEFAULT = 30#通知刷新时间

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=254)
    mes = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    viewed = models.BooleanField(default=False, db_index=True)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_messages', on_delete=models.CASCADE)
    #receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_messages', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-timestamp']


    def __str__(self) -> str:#notification类的描写
        return f"{self.user}: {self.title}"

    def save(self, *args, **kwargs):
        # overriden save to ensure cache is invaidated on very call
        super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        # overriden delete to ensure cache is invaidated on very call
        super().delete(*args, **kwargs)


    def mark_viewed(self) -> None:# 将通知标记为已查看，并保存该更改。
        """Mark notification as viewed."""
        logger.info("Marking notification as viewed: %s" % self)
        self.viewed = True
        self.save()

notif/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from .models import Notification
from django.db.models import Q
from django.conf import settings


logger = logging.getLogger(__name__)
User = get_user_model()

@login_required
def notification_list(request):
    logger.debug("notification_list called by user %s" % request.user)
    #notifications_qs = Notification.objects.filter(user=request.user).order_by("-timestamp")
    notifications_qs = Notification.objects.filter(Q(sender=request.user) | Q(user=request.user)).order_by("-timestamp")
    new_notifs = notifications_qs.filter(viewed=False)
    old_notifs = notifications_qs.filter(viewed=True)
    logger.debug(
        "User %s has %s unread and %s read notifications",
        request.user,
        len(new_notifs),
        len(old_notifs)
    )
    context = {
        'read': old_notifs,
        'unread': new_notifs,
    }
    return render(request, 'list.html', context)
    new_notifs = notifications_qs.filter(viewed=False)
    old_notifs = notifications_qs.filter(viewed=True)
    logger.debug(
        "User %s has %s unread and %s read notifications",
        request.user,
        len(new_notifs),
        len(old_notifs)
    )
    context = {
        'read': old_notifs,
        'unread': new_notifs,
    }
    return render(request, 'list.html', context)


@login_required
def notification_view(request, notif_id):
    logger.debug(
        "notification_view called by user %s for notif_id %s",
        request.user,
        notif_id
    )
    notif = get_object_or_404(Notification, pk=notif_id)
    if notif.user == request.user:
        logger.debug("Providing notification for user %s", request.user)
        context = {'notif': notif}
        notif.mark_viewed()
        return render(request, 'view.html', context)
    else:
        logger.warning(
            "User %s not authorized to view notif_id %s belonging to user %s",
            request.user,
            notif_id, notif.user
        )
        messages.error(request, _('You are not authorized to view that notification.'))
        return redirect('notif:notiflist')


@login_required
def remove_notification(request, notif_id):
    logger.debug(
        "remove notification called by user %s for notif_id %s",
        request.user,
        notif_id
    )
    notif = get_object_or_404(Notification, pk=notif_id)
    if notif.user == request.user:
        if Notification.objects.filter(id=notif_id).exists():
            notif.delete()
            logger.info("Deleting notif id %s by user %s", notif_id, request.user)
            messages.success(request, _('Deleted notification.'))
    else:
        logger.error(
            "Unable to delete notif id %s for user %s - notif matching id not found.",
            notif_id,
            request.user
        )
        messages.error(request, _('Failed to locate notification.'))
    return redirect('notif:notiflist')


@login_required
def mark_all_read(request):
    logger.debug('mark all notifications read called by user %s', request.user)
    Notification.objects.filter(user=request.user).update(viewed=True)
    messages.success(request, _('Marked all notifications as read.'))
    return redirect('notif:notiflist')


@login_required
def delete_all_read(request):
    logger.debug('delete all read notifications called by user %s', request.user)
    Notification.objects.filter(user=request.user).filter(viewed=True).delete()
    messages.success(request, _('Deleted all read notifications.'))
    return redirect('notif:notiflist')


def user_notifications_count(request, user_pk: int):
    """returns to notifications count for the give user as JSON

    This view is public and does not require login
    """
    unread_count = Notification.objects.user_unread_count(user_pk)
    data = {'unread_count': unread_count}
    return JsonResponse(data, safe=False)

@login_required
def leave_message(request, receiver_username):
    if request.method == 'POST':
        user = User.objects.get(username=receiver_username)
        content = request.POST.get('content')
        imessage = Notification(sender=request.user, user=user, mes=content)
        imessage.save()
        messages.success(request, 'Message sent successfully.')
        return redirect('notif:notiflist')
    else:
        return render(request, 'send_message.html')  # Create a template for sending messages

notif/templates/list.html
{% extends "bbs/base.html" %}
{% load i18n %}

<head>
      <link rel="stylesheet" type="text/css" href="bu.css">
</head>

{% block page_title %}{% translate "通知" %}{% endblock %}

{% block content %}
    <h1 class="page-header text-center">{% translate "通知" %}</h1>

    <div class="panel panel-default">

        <div class="panel-heading clearfix">
            <ul class="nav nav-pills navbar-left">
                <li class="active"><a data-toggle="tab" href="#unread">{% translate "未读" %}<b>({{ unread|length }})</b></a></li>
                <li><a data-toggle="tab" href="#read">{% translate "已读" %} <b>({{ read|length }})</b></a></li>
            </ul>


            <ul class="nav nav-pills navbar-left">
                <li class="active"><a href="{% url 'notif:notifmar' %}" >{% translate "标记所有未读"  %}</a></li>
                <li> <a href="{% url 'notif:notifdar' %}" >{% translate "删除所有已读" %}</a></li>
            </ul>


        </div>

        <div class="panel-body">
            <div class="tab-content">

                <div id="unread" class="tab-pane fade in active">
                    {% include "list_partial.html" with notifications=unread %}
                </div>

                <div id="read" class="tab-pane fade">
                    {% include "list_partial.html" with notifications=read %}
                </div>

            </div>
        </div>

    </div>
{% endblock %}

notif/templates/list_partial.html
{% load i18n %}

{% if notifications %}
    <div class="table-responsive">
        <table class="table table-condensed table-hover table-striped">
            <tr>
                <th class="text-center">{% translate "时间" %}</th>
                <th class="text-center">{% translate "内容" %}</th>
                <th class="text-center">{% translate "发出者" %}</th>
                <th class="text-center">{% translate "接收者" %}</th>
            </tr>
            {% for notification in notifications %}
                <tr>
                    <td class="text-center">{{ notification.timestamp }}</td>
                    <td class="text-center">{{ notification.mes }}</td>
                    <td class="text-center">{{ notification.sender.username }}</td>
                    <td class="text-center">{{ notification.user.username }}</td>

                        <a href="{% url 'notif:notifview' notification.id %}" class="btn btn-primary" title="View">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <a href="{% url 'notif:notifrm' notification.id %}" class="btn btn-danger" title="Remove">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endif %}

notif/templates/send_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/static/img/bbs_demo_icon.ico"/>
    <title>编辑留言</title>
</head>
<body>
{% extends "bbs/base.html" %}
{% block content %}
    <h1>留言</h1>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ 留言 }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <label for="content">消息内容:</label><br>
        <textarea name="content" id="content" cols="30" rows="5"></textarea><br>
        <input type="submit" value="发送">
    </form>

    <a href="{% url 'notif:notiflist' %}">查看消息列表</a>
{% endblock content %}
</body>
</html>

notif/templates/view.html
{% extends "bbs/base.html" %}
{% load i18n %}

{% block page_title %}{% translate "View Notification" %}{% endblock page_title %}

{% block content %}
    <h1 class="page-header text-center">
        {% translate "View Notification" %}
        <div class="text-right">
            <a href="{% url 'notif:list' %}" class="btn btn-primary btn-lg">
                <span class="glyphicon glyphicon-arrow-left"></span>
            </a>
        </div>
    </h1>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-{{ notif.level }}">
                <div class="panel-heading">{{ notif.timestamp }} {{ notif.title }}</div>
                <div class="panel-body"><pre>{{ notif.message }}</pre></div>
            </div>
        </div>
    </div>

{% endblock %}