bbs/urls.py
from django.urls import path
from bbs import views
from chat.views import user_info
from notif.views import leave_message


app_name = 'bbs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 板块页面
    path('plate=<int:plate_id>&page=<int:page>', views.plate, name='plate'),
    # 帖子详情页
    path('article=<int:article_id>&page=<int:page>', views.article, name='article'),
    # 发表帖子页面
    path('plate=<int:plate_id>/post', views.post, name='post'),
    # 发表回复页面
    path('article=<int:article_id>/reply', views.reply, name='reply'),
    # 用户发帖记录页面
    path('user/my_article', views.my_article, name='my_article'),
    # 用户回复记录页面
    path('user/my_comment', views.my_comment, name='my_comment'),
    # 编辑帖子页面
    path('article=<int:article_id>/edit', views.edit_article, name='edit_article'),
    # 编辑回复
    path('comment=<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    # 删除帖子页面
    path('article=<int:article_id>/delete', views.delete_article, name='delete_article'),
    # 删除回复页面
    path('comment=<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    # 查询页面
    path('search/', views.search, name='search'),
    # 开发者邮箱
    path('mailbox/',views.mailbox,name = 'mailbox'),
    # 留言页面
    path('user_info/<str:username>', user_info, name='user_info'),
    # 留言板展示
    path('mailboard/',views.mailshow,name = 'mailshow'),
    # 留言页面
    path('notif/leave_message/<str:receiver_username>', leave_message, name='leavemes'),
]

bbs_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('bbs.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('notif/', include('notif.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users import views
from django.conf import settings
from django.conf.urls.static import static

# ... 你的其他URL配置 ...


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name='register'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('update_sno/', views.update_sno, name='update_sno'),
    path('update_phone/', views.update_phone, name='update_phone'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_name/', views.update_name, name='update_name'),
    path('update_sno/', views.update_sno, name='update_sno'),
    path('update_phone/', views.update_phone, name='update_phone'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_name/', views.update_name, name='update_name'),
    path('update_info/<str:username>', views.update_info, name='update_info'),
    path('update_avatar/', views.update_avatar, name='update_avatar'),
    #path('my-image/',views.my_image,name = "my_image")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
# Create your models here.
class Plate(models.Model):
    """板块"""
    text = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.text}'


class Article(models.Model):
    """帖子主体"""
    plate = models.ForeignKey(Plate, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'articles'

    def __str__(self):
        return f'{self.text[:50]}'


class Comment(models.Model):
    """帖子回复"""
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'comments'

    def __str__(self):
        return f'{self.text[:50]}...'

class Message(models.Model):
    name = models.CharField(max_length=100, null =True)
    email = models.EmailField(null=True)
    timestamp = models.DateTimeField(default = timezone.now)
    content = models.TextField()

    def __str__(self):
        return f'{self.name}({self.email})-{self.timestamp}'

bbs/forms.py
from django import forms
from bbs.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}

bbs/views.py
from django.shortcuts import render, redirect
from bbs.models import Plate, Article, Comment,Message
from bbs.forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
def index(request):
    """bbs主页"""
    plates = Plate.objects.all()
    context = {'plates': plates}
    return render(request, 'bbs/index.html', context)


def plate(request, plate_id, page):
    """板块页面"""
    plate = Plate.objects.get(id=plate_id)
    articles = plate.article_set.order_by('-date_added')

    page_size = 20    # 每页显示的帖子条目数量
    length = len(articles)
    page_num = length / page_size
    if page_num != int(page_num):
        page_num += 1
    page_num = int(page_num)
    # 分页器
    temp = int(page / 10)
    page_group = 10    # 单页显示的页码数量
    if page_num < page_group:
        page_range = range(1, page_num+1)
    if page <= page_num:
        if not page % page_group:
            start_page = (temp - 1) * page_group + 1
            page_range = range(start_page, page+1)
        else:
            if (temp + 1) * page_group < page_num:
                start_page = temp * page_group + 1
                end_page = (temp + 1) * page_group
                page_range = range(start_page, end_page+1)
            else:
                start_page = temp * page_group + 1
                page_range = range(start_page, page_num+1)
    else:
        page = page_num
        if page_num % page_group:
            start_page = int(page_num/page_group) * page_group + 1
            page_range = range(start_page, page_num+1)
        else:
            page_range = range(page_num-page_group+1, page_num+1)
    # 翻页器
    if page != 1:
        previous_page = page - 1
    else:
        previous_page = page
    if page != page_num:
        next_page = page + 1
    else:
        next_page = page

    if articles:
        start = (page - 1) * page_size
        end = page * page_size
        data = articles[start:end]
        articles = data

    context = {
        'plate': plate,
        'articles': articles,
        'present_page': page,
        'previous_page': previous_page,
        'next_page': next_page,
        'page_range': page_range,
    }
    return render(request, 'bbs/plate.html', context)


def article(request, article_id, page):
    """帖子详情页"""
    article = Article.objects.get(id=article_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.article_id = article_id
            new_comment.owner_id = request.user.id
            new_comment.save()
            return redirect('bbs:article', article_id=article_id, page = 1)
    comments = article.comment_set.order_by('date_added')

    page_size = 20    # 每页显示的帖子条目数量
    length = len(comments) + 1
    page_num = length / page_size
    if page_num != int(page_num):
        page_num += 1
    page_num = int(page_num)
    # 分页器
    temp = int(page / 10)
    page_group = 10  # 单页显示的页码数量
    if page_num < page_group:
        page_range = range(1, page_num + 1)
    if page <= page_num:
        if not page % page_group:
            start_page = (temp - 1) * page_group + 1
            page_range = range(start_page, page + 1)
        else:
            if (temp + 1) * page_group < page_num:
                start_page = temp * page_group + 1
                end_page = (temp + 1) * page_group
                page_range = range(start_page, end_page + 1)
            else:
                start_page = temp * page_group + 1
                page_range = range(start_page, page_num + 1)
    else:
        page = page_num
        if page_num % page_group:
            start_page = int(page_num / page_group) * page_group + 1
            page_range = range(start_page, page_num + 1)
        else:
            page_range = range(page_num - page_group + 1, page_num + 1)
    # 翻页器
    if page != 1:
        previous_page = page - 1
    else:
        previous_page = page
    if page != page_num:
        next_page = page + 1
    else:
        next_page = page

    if comments:
        # 帖子一楼占一栏, 故第 1 页显示回复的数量减 1
        if page == 1:
            start = 0
            end = page * page_size - 1
        # 后续页需整体向前 1 位, 保证每页回复数量一致
        else:
            start = (page - 1) * page_size - 1
            end = page * page_size - 1
        data = comments[start:end]
        comments = data

    context = {
        'article': article,
        'comments': comments,
        'present_page': page,
        'previous_page': previous_page,
        'next_page': next_page,
        'page_range': page_range,
    }
    return render(request, 'bbs/article.html', context)


@login_required
def post(request, plate_id):
    """发帖页面"""
    plate = Plate.objects.get(id=plate_id)

    if request.method != 'POST':
        form = ArticleForm()
    else:
        form = ArticleForm(data=request.POST)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.plate_id = plate_id
            new_article.owner_id = request.user.id
            new_article.save()
            return redirect('bbs:plate', plate_id=plate.id, page=1)

    context = {'plate': plate, 'form': form}
    return render(request, 'bbs/post.html', context)


@login_required
def reply(request, article_id):
    """回复页面"""
    article = Article.objects.get(id=article_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.article_id = article_id
            new_comment.owner_id = request.user.id
            new_comment.save()
            return redirect('bbs:article', article_id=article_id,page = 1)

    context = {'article': article, 'form': form}
    return render(request, 'bbs/reply.html', context)


@login_required
def edit_article(request, article_id):
    """编辑帖子页面"""
    article = Article.objects.get(id=article_id)
    if article.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = ArticleForm(instance=article)
    else:
        form = ArticleForm(instance=article, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('bbs:my_article')

    context = {'article': article, 'form': form}
    return render(request, 'bbs/edit_article.html', context)


@login_required
def edit_comment(request, comment_id):
    """编辑回复页面"""
    comment = Comment.objects.get(id=comment_id)
    if comment.owner != request.user:
        raise Http404


    if request.method != 'POST':
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('bbs:my_comment')

    context = {'comment': comment, 'form': form}
    return render(request, 'bbs/edit_comment.html', context)


@login_required
def delete_article(request, article_id):
    """删除帖子页面"""
    article = Article.objects.get(id=article_id)
    if article.owner != request.user:
        raise Http404
    article.delete()
    return redirect('bbs:my_article')


@login_required
def delete_comment(request, comment_id):
    """删除回复页面"""
    comment = Comment.objects.get(id=comment_id)
    if comment.owner != request.user:
        raise Http404
    comment.delete()
    return redirect('bbs:my_comment')


@login_required
def my_article(request):
    """用户发帖记录页面"""
    articles = Article.objects.filter(owner=request.user).order_by('-date_added')
    context = {'articles': articles}
    return render(request, 'bbs/my_article.html', context)


@login_required
def my_comment(request):
    """用户回复记录页面"""
    comments = Comment.objects.filter(owner=request.user).order_by('-date_added')
    context = {'comments': comments}
    return render(request, 'bbs/my_comment.html', context)

@login_required
def search(request):
    """查询页面"""
    keyword = request.GET.get('keyword', '')
    condition = request.GET.get('condition', '')
    page = int(request.GET.get('page', 1))

    if condition == 'content':
        articles = Article.objects.filter(text__contains=keyword).order_by('-date_added')
    elif condition == 'title':
        articles = Article.objects.filter(title__contains=keyword).order_by('-date_added')
    elif condition == 'plate':
        articles = Article.objects.filter(plate__text__contains=keyword).order_by('-date_added')
    elif condition == 'date':
        articles = Article.objects.filter(date_added__contains=keyword).order_by('-date_added')
    elif condition == 'owner':
        articles = Article.objects.filter(owner__username__contains=keyword).order_by('-date_added')
    else:
        articles = []

    page_size = 20
    length = len(articles)
    page_num = length / page_size
    if page_num != int(page_num):
        page_num += 1
    page_num = int(page_num)
    temp = int(page / 10)
    page_group = 10
    if page_num < page_group:
        page_range = range(1, page_num + 1)
    if page <= page_num:
        if not page % page_group:
            start_page = (temp - 1) * page_group + 1
            page_range = range(start_page, page + 1)
        else:
            if (temp + 1) * page_group < page_num:
                start_page = temp * page_group + 1
                end_page = (temp + 1) * page_group
                page_range = range(start_page, end_page + 1)
            else:
                start_page = temp * page_group + 1
                page_range = range(start_page, page_num + 1)
    else:
        page = page_num
        if page_num % page_group:
            start_page = int(page_num / page_group) * page_group + 1
            page_range = range(start_page, page_num + 1)
        else:

bbs/templates/bbs/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/static/img/bbs_demo_icon.ico"/>
    <link rel="stylesheet" href="/static/markdown/dist/simplemde.min.css">
    <script src="/static/markdown/dist/simplemde.min.js"></script>
    <script src="/static/jQuery.js"></script>
    <title>帖子详情</title>
    <style>
         h1{
      font-family: 'Brush Script MT', cursive;
      font-size: 50px;
      border-bottom: 2px dashed;
      margin-top: 10px;
  }
    .to-plate{
  padding: 10px;
  color: #fff;
  border-radius: 30px;
  text-decoration: none;
  background: #6E50E9;
  position: absolute;
  width: 150px;
  height: 15px;
  line-height: 40px;
  font-size: 16px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: -15px;
    }
    .to-plate:hover{
    background-color: mediumpurple;
    }

     a.reply-page1{
    position: relative;
    top: 30px;
    left: 6px;
    width: 150px;
    height: 15px;
    color: #fff;
    text-align: center;
    text-decoration: none;
    background-color: #6E50E9;
    padding: 10px;
    border-radius: 30px;
    line-height: 40px;
    font-size: 16px;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: -66px;
    margin-left: 200px;
}
 a.reply-page1:hover{
    background-color: mediumpurple;
}

    .article-content1{
    position: relative;
    min-height: 0px;
}
    .article-content2{
    position: relative;
    min-height: 160px;
}
.user-info1, .article-text1{
    position: absolute;
    top: 0;
    bottom: 0;
}
.user-info1{
    width: 98px;
    left: 0;
    border-top: 1px solid #d8d8d8;
    border-right: 2px solid #e3e3e3;
    background-color: #fff;

  justify-content: center;
}
.user-info1 p{
    text-align: center;
}
.article-text2{
    display: inline-flex;
    position: relative;
    flex-direction: column;
    width: 980px;
    border-top: 1px solid #e3e3e3;
    background-color: #fff;
}
.article-text1{
    display: inline-flex;
    position: relative;
    flex-direction: column;
    width: 882px;
    left: 98px;
    border-top: 1px solid #e3e3e3;
    background-color: #fff;
}
.comment-text{
    display: inline-flex;
    position: relative;
    flex-direction: column;
    width: 882px;
    min-height: 160px;
    left: 98px;
    border-top: 1px solid #e3e3e3;
    background-color: #fff;
}
.article-text1 span, .comment-text span{
    padding: 14px 24px 0 24px;
    margin: 0;
    background-color: #fff;
}
.article-text2 span{
    padding: 14px 24px 0 24px;
    margin: 0;
    background-color: #fff;
}
.article-text1 span:first-child, .comment-text span:last-child{
    position: absolute;
    top: 0;
    right: 0;
    margin: 4px 0;
    color: #999;
}
.refresh-btn1 a{
    display: flex;
    position: fixed;
    bottom: 72%;
    right: 2%;
    width: 150px;
    color: #fff;
    text-align: center;
    text-decoration: none;
    border-radius: 5px;
    background-color: #51a970;
    line-height: 40px;
    font-size: 16px;
    justify-content: center;
    align-items: center;
}
.refresh-btn1 a:hover{
    background-color: #408458;
}

.button{
        background-color: mediumpurple;
        text-decoration: none;
        color: white;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-left: 7px;
        padding-right: 7px;
        border-radius: 5px;
    }

.time{
    text-align: right;
}
    </style>
</head>
<body>
{% extends "bbs/base.html" %}
{% load myfileter %}
{% block content %}
    <div class="content-box">
        <div class="page-head">
            <h1>article in {{ article.plate.text }}</h1>
            <a class="to-plate" href="{% url 'bbs:plate' article.plate.id 1 %}">返回论坛</a>
            <br>
            <a class="reply-page1" href="{% url 'bbs:reply' article.id %}">发表回复 &raquo</a>
        </div>
    <br><br><br><br>
        <!--主贴内容-->
        <div style="background-color: #f3f3f3;border-radius: 20px" class="article-box">
            <div style="background-color: darkgrey;margin-left:-98px;width:956px;border-radius: 20px 20px 0 0" class="article-title">
                <p style="font-size: 24px;margin-left: 0px;padding: 5px 0 -30px -11px">{{ article.title|mdToHtml|safe }}</p>
            </div>
            {% if present_page == 1 %}
                <div class="article-content1">
                    <div class="user-info1">
                        {% if article.owner.avatar %}
                            <div style="width: 60px; height: 60px;border-radius: 50%;   margin-right: 7px;overflow: hidden;  ">
                                <img src="{{ article.owner.avatar.url }}" alt="{{article.owner.username }}'s avatar" style="width: 100%; height: 100%;margin-right: 20px;">
                            </div>
                        {% else %}
                            <div style="width: 60px;height: 60px;border-radius: 50%;   margin-right: 7px; overflow: hidden;" >
                                <img src=/static/img/path-to-default-avatar.jpg alt="Default avatar" style="width: 100%; height: 100%;margin-right: 20px;">
                            </div>

                        {% endif %}
                        <a class="button" href={% url 'bbs:user_info' username=article.owner.username %}>{{ article.owner.username }}</a>
                    </div>
                    <div class="article-text1">
                    <br><br>
                        <br><br>

                    </div>
                </div>
                <div style="border-radius: 0 0 20px 20px " class="article-content2">
                    <div style="border-radius: 0 0 20px 20px " class="article-text2">
                        <div style="border-radius: 0 0 20px 20px;white-space: normal;min-height: 160px;word-wrap: break-word">{{ article.text|mdToHtml|safe }}</div>
                        <div class="time" style="margin-right: 50px">{{ article.date_added|date:'M d, Y H:i' |mdToHtml|safe}}</div><br><br>
                    </div>
                </div>
            {% endif %}
        <br>
        <!--回复内容-->
        <div class="comment-list" style="clear: both">
            {% for comment in comments %}
                <div style="margin-top: 5px;border-radius: 10px" class="comment-content">
                    <div style="border-radius: 10px 0 0 10px;background-color: darkgrey" class="user-info">
                        {% if comment.owner.avatar %}
                            <div style="width: 60px; height: 60px;border-radius: 50%;   margin-right: 7px;overflow: hidden;  ">
                                <img src="{{ comment.owner.avatar.url }}" alt="{{comment.owner.username }}'s avatar" style="width: 100%; height: 100%;margin-right: 20px;">
                            </div>
                        {% else %}
                            <div style="width: 60px;height: 60px;border-radius: 50%;   margin-right: 7px; overflow: hidden;" >
                                <img src=/static/img/path-to-default-avatar.jpg alt="Default avatar" style="width: 100%; height: 100%;margin-right: 20px;">
                            </div>

                        {% endif %}
                        <a class="button" href={% url 'bbs:user_info' username=comment.owner.username  %}>{{ comment.owner.username }}</a>                     </div>

                    <div style="border-radius:0 10px 10px 0" class="comment-text">
                        <div style="border-radius:0 10px 10px 0;white-space: normal;min-height: 160px;word-wrap: break-word">{{ comment.text|mdToHtml|safe }}</div><br/>
                        <div class="time" style="border-radius:0 10px 10px 0;margin-right: 50px">{{ comment.date_added|date:'M d, Y H:i'|mdToHtml|safe }}</div>
                    </div>
                </div>
            {% empty %}
                <p>暂时还没有回复</p>
            {% endfor %}
        </div>
        <!--分页器-->
        {% if previous_page > 0 %}
            <div class="turn-page">
                <ul>
                    {% if present_page != 1 %}
                        <li class="previous-page"><a href="{% url 'bbs:article' article.id previous_page %}">上一页</a></li>
                    {% endif %}
                    {% for page in page_range %}
                        {% if page == present_page %}
                            <li><a class="active" href="{% url 'bbs:article' article.id page %}">{{ page }}</a> </li>
                        {% else %}
                            <li><a href="{% url 'bbs:article' article.id page %}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    <li><a href="{% url 'bbs:article' article.id next_page %}">下一页</a></li>
                </ul>
            </div>
        {% endif %}
        <!--快速回复-->
        <div class="reply-box">
            {% if user.is_authenticated %}
                <form action="{% url 'bbs:article' article.id 1 %}" method="post">
                    {% csrf_token %}
                    <div style="border-radius: 5px 5px 0 0 " class="quick-reply-head">
                        <span>快速回复</span>
                    </div>
                    <div class="quick-reply-text">
                        <label for="id_text">
                            <textarea style="border-radius: 0 0 5px 5px" name="text" id="text"></textarea>
                        </label>
                    </div>
                    <button class="reply-btn" name="submit">回复</button>
                </form>
            {% endif %}
        </div>
    </div>

    <div class="refresh-btn1">
        <a href="{% url 'bbs:article' article.id present_page %}">刷新</a>
    </div>
    </div>

    <script>
    let simplemde;
    simplemde = new SimpleMDE(
        {
            autosave: {
                "enabled": true,
                "uniqueId": "MyUniqueID",
                "delay": 1000,
            },
            element: $('textarea[name=text]')[0],
            spellcheck: false,
            autoDownloadFontAwesome: true,
        }
    );
</script>

{% endblock %}
</body>
</html>

bbs/templates/bbs/edit_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/static/img/bbs_demo_icon.ico"/>
    <link rel="stylesheet" href="/static/markdown/dist/simplemde.min.css">
    <script src="/static/markdown/dist/simplemde.min.js"></script>
    <script src="/static/jQuery.js"></script>
    <title>编辑帖子</title>
    <style>
    .to-plate{
  padding: 10px;
  color: #fff;
  border-radius: 30px;
  text-decoration: none;
  background: #6E50E9;
  position: absolute;
  width: 150px;
  height: 15px;
  line-height: 40px;
  font-size: 16px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: -15px;
    }
    .to-plate:hover{
    background-color: mediumpurple;
    }
    </style>
</head>
<body>
{% extends "bbs/base.html" %}
{% block content %}
    <div class="content-box">
        <div style="margin-top: 50px" class="page-head">
            <a class="to-plate" href="{% url 'bbs:plate' article.plate.id 1 %}">返回forum {{ article.plate.text }}</a>
        </div>

        <form action="{% url 'bbs:edit_article' article.id %}" method="post">
            {% csrf_token %}
            <div style="margin-top: -70px" class="post-box">
                 <div style="border-radius: 5px 5px 0 0 " class="quick-reply-head">
                        <span>编辑帖子</span>
                 </div>
                <div class="post-title">
                    <label for="id_title">
                        <input type="text" name="title" id="title" value={{ article.title }} placeholder="标题"/>
                    </label>
                </div>
                <div class="post-text">
                    <label for="id_text">
                        <textarea style="border-radius:0 0 5px 5px" name="text" id="text">{{ article.text }}</textarea>
                    </label>
                </div>
                <button class="post-btn" name="submit">提交</button>
            </div>
        </form>
    </div>
    <script>
    let simplemde;
    simplemde = new SimpleMDE(
        {
            autosave: {
                "enabled": true,
                "uniqueId": "MyUniqueID",
                "delay": 1000,
            },
            element: $('textarea[name=text]')[0],
            spellcheck: false
        }
    );
</script>
{% endblock content %}
</body>

</html>

bbs/templates/bbs/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/static/img/bbs_demo_icon.ico"/>
    <link rel="stylesheet" href="/static/markdown/dist/simplemde.min.css">
    <script src="/static/markdown/dist/simplemde.min.js"></script>
    <script src="/static/jQuery.js"></script>
    <title>发表帖子</title>
    <style>
         h1{
      font-family: 'Brush Script MT', cursive;
      font-size: 50px;
      border-bottom: 2px dashed;
      margin-top: 10px;
  }
    .to-plate{
  padding: 10px;
  color: #fff;
  border-radius: 30px;
  text-decoration: none;
  background: #6E50E9;
  position: absolute;
  width: 150px;
  height: 15px;
  line-height: 40px;
  font-size: 16px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: -15px;
    }
    .to-plate:hover{
    background-color: mediumpurple;
    }
    </style>
</head>
<body>
{% extends "bbs/base.html" %}

{% block content %}
    <div class="content-box">
        <div class="page-head">
            <h1>forum {{ plate.text }}</h1>
            <a class="to-plate" href="{% url 'bbs:plate' plate.id 1 %}">返回forum</a>
        </div>
        <br><br><br>
        <!--发帖输入-->
        <form action="{% url 'bbs:post' plate.id %}" method="post">
            {% csrf_token %}
            <div class="post-box">
                <div class="post-head"><span>发表帖子</span></div>
                <div class="post-title">
                    <label for="id_title">
                        <input type="text" name="title" id="title" placeholder="标题"/>
                    </label>
                </div>
                <div class="post-text">
                    <label for="id_text">
                        <textarea name="text" id="text"></textarea>
                    </label>
                </div>
                <button class="post-btn" name="submit">提交</button>
            </div>
        </form>
    </div>

    <script>
    let simplemde;
    simplemde = new SimpleMDE(
        {
            autosave: {
                "enabled": true,
                "uniqueId": "MyUniqueID",
                "delay": 1000,
            },
            element: $('textarea[name=text]')[0],
            spellcheck: false,
            autoDownloadFontAwesome: true,
        }
    );
</script>
{% endblock content %}

</body>
</html>