bbs/urls.py
from django.urls import path
from bbs import views
from chat.views import user_info
from notif.views import leave_message


app_name = 'bbs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 板块页面
    path('plate=<int:plate_id>&page=<int:page>', views.plate, name='plate'),
    # 帖子详情页
    path('article=<int:article_id>&page=<int:page>', views.article, name='article'),
    # 发表帖子页面
    path('plate=<int:plate_id>/post', views.post, name='post'),
    # 发表回复页面
    path('article=<int:article_id>/reply', views.reply, name='reply'),
    # 用户发帖记录页面
    path('user/my_article', views.my_article, name='my_article'),
    # 用户回复记录页面
    path('user/my_comment', views.my_comment, name='my_comment'),
    # 编辑帖子页面
    path('article=<int:article_id>/edit', views.edit_article, name='edit_article'),
    # 编辑回复
    path('comment=<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    # 删除帖子页面
    path('article=<int:article_id>/delete', views.delete_article, name='delete_article'),
    # 删除回复页面
    path('comment=<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    # 查询页面
    path('search/', views.search, name='search'),
    # 开发者邮箱
    path('mailbox/',views.mailbox,name = 'mailbox'),
    # 留言页面
    path('user_info/<str:username>', user_info, name='user_info'),
    # 留言板展示
    path('mailboard/',views.mailshow,name = 'mailshow'),
    # 留言页面
    path('notif/leave_message/<str:receiver_username>', leave_message, name='leavemes'),
]

bbs_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('bbs.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('notif/', include('notif.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users import views
from django.conf import settings
from django.conf.urls.static import static

# ... 你的其他URL配置 ...


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name='register'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('update_sno/', views.update_sno, name='update_sno'),
    path('update_phone/', views.update_phone, name='update_phone'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_name/', views.update_name, name='update_name'),
    path('update_sno/', views.update_sno, name='update_sno'),
    path('update_phone/', views.update_phone, name='update_phone'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_name/', views.update_name, name='update_name'),
    path('update_info/<str:username>', views.update_info, name='update_info'),
    path('update_avatar/', views.update_avatar, name='update_avatar'),
    #path('my-image/',views.my_image,name = "my_image")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/%Y/%m/%d/', null=True, blank=True,default="path-to-default-avatar.jpg")  # 头像
    Sno = models.CharField(max_length=20, unique=True)  # 学号
    phone = models.CharField(max_length=15, blank=True, null=True)  # 电话
    email = models.EmailField(unique=True, verbose_name="邮箱")

    def __str__(self):
        return 'user{}'.format(self.username)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
 avatar = forms.ImageField(required=False)
 Sno = forms.CharField(max_length=50, required=True)
 phone = forms.CharField(max_length=15, required=True)
 email = forms.EmailField(required=True)
 class Meta:
  model = CustomUser
  fields = ("username", "email","Sno","phone","avatar","password1","password2")

class SnoUpdateForm(forms.ModelForm):
 class Meta:
  model = CustomUser
  fields = ['Sno']

class PhoneUpdateForm(forms.ModelForm):
 class Meta:
  model = CustomUser
  fields = ['phone']

class AvatarUpdateForm(forms.ModelForm):
 class Meta:
  model = CustomUser
  fields = ['avatar']
class EmailUpdateForm(forms.ModelForm):
 class Meta:
  model = CustomUser
  fields = ['email']

class NameUpdateForm(forms.ModelForm):
 class Meta:
  model = CustomUser
  fields = ['username']

class VerificationCodeForm(forms.Form):
 verification_code = forms.CharField(max_length=6, label='验证码', required=True)

users/views.py
import os.path

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.http import HttpResponse
import random
import string
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import SnoUpdateForm,PhoneUpdateForm,EmailUpdateForm,NameUpdateForm,VerificationCodeForm,AvatarUpdateForm
from users.models import CustomUser
from django.conf import settings
# Create your views here.
def register(request):
    """注册页面"""
    if request.method != 'POST':
        form = CustomUserCreationForm()
    else:
        print(request.POST)
        print(request.FILES)

        form = CustomUserCreationForm(request.POST,request.FILES)
        if form.is_valid():
            user_code = request.POST.get('verification_code', '')
            real_code = request.session.get('verification_code', '')
            if user_code != real_code:
                # 处理验证码不匹配的情况...
                messages.error(request, "验证码不匹配，请重试。")
                return render(request, 'registration/register.html')  # 返回到同一注册页面
            else:
                # 处理验证码匹配的情况...
                # ...例如创建用户、登录用户...
                print(form.cleaned_data['avatar'])
                new_user = form.save(commit = False)
                avatar = form.cleaned_data['avatar']
                new_user.avatar = avatar
                #file_path = os.path.join(settings.MEDIA_ROOT, 'avatars', new_user.avatar)
                #new_user.avatar.save(file_path,new_user.avatar)
                new_user.save()

                login(request, new_user)
                messages.success(request, "注册成功！")
                return redirect('bbs:index')
        else:
            print(form.errors)
            return HttpResponse("Sorry,your password is too simple or your account has been used.")
    context = {'form': form}
    return render(request, 'registration/register.html', context)


@csrf_exempt
def send_verification_code(request):
    email = request.POST.get('email', '')
    code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))

    # 存储code到session以便稍后验证
    request.session['verification_code'] = code

    # 发送邮件（在生产环境中应该异步完成）
    try:
        send_mail('你的验证码', '你的验证码是: ' + code, '2307302370@qq.com', [email], fail_silently=False)
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)})

@login_required
def update_sno(request):
    if request.method == 'POST':
        form = SnoUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:update_info', username=request.user.username)  # 重定向到用户信息页面
    else:
        form = SnoUpdateForm(instance=request.user)
    return render(request, 'update/update_sno.html', {'form': form})

@login_required
def update_avatar(request):
    if request.method == 'POST':
        # 获取用户上传的头像文件
        new_avatar = request.FILES.get('avatar')
        # 检查用户是否上传了头像
        if new_avatar:
            # 保存新头像到用户的数据库记录
            request.user.avatar = new_avatar
            request.user.save()
            messages.success(request, '头像已更新')
            return redirect('users:update_info', username=request.user.username)  # 重定向到用户信息页面
        else:
            messages.error(request, '请选择一个有效的头像文件')

    return render(request, 'update/update_avatar.html')


@login_required
def update_phone(request):
    if request.method == 'POST':
        form = PhoneUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:update_info', username=request.user.username)  # 重定向到用户信息页面
    else:
        form = PhoneUpdateForm(instance=request.user)
    return render(request, 'update/update_phone.html', {'form': form})

@login_required
def update_email(request):
    """修改email"""
    if request.method == 'POST':
        form = EmailUpdateForm(request.POST,instance=request.user)
        if form.is_valid():
            user_code = request.POST.get('verification_code', '')
            real_code = request.session.get('verification_code', '')
            if user_code != real_code:
                messages.error(request, "验证码不匹配，请重试。")
                return render(request, 'update/update_email.html')  # 返回到同一注册页面
            else:
                # 处理验证码匹配的情况...
                form.save()
                return redirect('users:update_info', username=request.user.username)
    else:
        form = SnoUpdateForm(instance=request.user)
    return render(request, 'update/update_email.html', {'form': form})

@login_required
def update_name(request):
    if request.method == 'POST':
        form = NameUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:update_info', username=request.user.username)  # 重定向到用户信息页面
    else:
        form = NameUpdateForm(instance=request.user)
    return render(request, 'update/update_name.html', {'form': form})

@login_required
def update_info(request, username):
    try:
        user = CustomUser.objects.get(username=username)
    except CustomUser.DoesNotExist:
        # 处理用户不存在的情况，例如返回错误页面或重定向到其他地方
        pass
    Sender_info={
        'username':request.user.username
    }
    CustomUser_info = {
        'username': user.username,
        'email': user.email,
        'phone':user.phone,
        'Sno':user.Sno,
        'Imag':user.avatar
        # 添加其他需要的字段
    }
    context = {
        'Sender_info':Sender_info,
        'CustomUser_info': CustomUser_info,
    }

    return render(request, 'update/update_info.html', context)

users/templates/update/update_avatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update avatar</title>

     <style>
            .button{
        background-color: mediumpurple;
        text-decoration: none;
        color: white;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-left: 7px;
        padding-right: 7px;
        border-radius: 5px;
    }
    </style>
</head>
<body>
 {% extends "bbs/base.html" %}

    {% block content %}

    <h1>上传头像</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="avatar">
        <button class="button" type="submit">上传头像</button>
    </form>

{% endblock %}
</body>
</html>

users/templates/update/update_email.html
{% extends "bbs/base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update email</title>
     <style>
            .button{
        background-color: mediumpurple;
        text-decoration: none;
        color: white;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-left: 7px;
        padding-right: 7px;
        border-radius: 5px;
    }
    </style>
</head>
<body>

    <div class="content-box">
        {% if form.erors %}
            <p>请输入正确的邮箱</p>
        {% endif %}

        <form action="{% url 'users:update_email' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <update_email-part>
            <div class="main">
                <!-- ... 其他输入字段 ... -->
                     <div class="inp">
				        <div class="right">
                           <input type="email" name="email" autocomplete="email" required="" id="id_email" placeholder="请输入邮箱">
                        </div>
                     </div>
                     <button style="width:100px " type="button" id="send_code_btn" class="button">发送验证码</button>
                     <div style="margin-top: 10px" class="inp">
				        <div  class="right">
                           <input  type="text" name="verification_code" required="" id="id_verification_code" placeholder="请输入验证码">
                        </div>
                     </div>

                <!-- ... 其他输入字段 ... -->

                <button id="myButton" name="submit" class="button">更 新</button>
                <input type="hidden" name="text" value="{% url 'bbs:index' %}"/>
            </div>
            </update_email-part>
        </form>
    </div>
    <!-- 确保已引入 jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#send_code_btn").click(function () {
                var email = $("#id_email").val();
                $.ajax({
                    url: "{% url 'users:send_verification_code' %}",
                    type: "POST",
                    data: {
                        email: email,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        if (data.success) {
                            alert("验证码已发送到你的邮箱");
                        } else {
                            alert("错误: " + data.error);
                        }
                    }
                });
            });
        });
    </script>

</body>
</html>
{% endblock content %}

users/templates/update/update_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人信息</title>
    <style>

        body{overflow: hidden;}
    .back-button{
  padding: 14px 16px;
  color: #fff;
  border: none;
  border-radius: 30px;
  text-decoration: none;
  background: #6E50E9;
  position: absolute;
  width: 80px;
  height: 20px;
  text-align: center;
  line-height: 40px;
  font-size: 16px;
  top: 100px;
  margin-left: 300px;
  transform: translateX(-50%);
  display: flex;
  flex-direction: column;
  align-items: center;


    }
    .back-button:hover{
    background-color: mediumpurple;
    }

    .container{
        margin: auto;
        background-color: white;
        border-radius: 10px;
        width: 60%;
        padding: 40px;
    }

    h2{
        font-weight: bold;
        border-bottom: solid 1px;
        padding-bottom: 5px;
        margin-bottom: 20px;
    }

    .button{
        background-color: mediumpurple;
        text-decoration: none;
        color: white;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-left: 7px;
        padding-right: 7px;
        border-radius: 5px;
    }
    </style>
</head>
<body>
    {% extends "bbs/base.html" %}

    {% block content %}

        <div class="container" style="margin-top: 30px;">
        <h2>个人信息修改:</h2>
        <div>
            <div style="width: 70%;">
                <span style="font-weight: bold;">Avatar:</span>
                    {% if user.avatar %}
                    <div style="width: 200px; height: 200px;margin-right: 7px;overflow: hidden;  ">
                    <img src="{{ user.avatar.url }}" alt="{{username }}'s avatar" style="width: 90%; height: 90%;margin-right: 20px;">
                    </div>
                    {% else %}
                     <div style="width: 200px;height: 200px;margin-right: 7px; overflow: hidden;" >
                         <img src=/static/img/path-to-default-avatar.jpg alt="Default avatar" style="width: 90%; height: 90%;margin-right: 20px;">
                     </div>
                    {% endif %}
            </div>
            <div style="width: 30%;">
                <a class="button" href="{% url 'users:update_avatar' %}">修改</a>
            </div>
        </div>
        <div>
            <div style="width: 70%;">
                <span style="font-weight: bold;">Username:</span> {{ CustomUser_info.username }}
            </div>
            <div style="width: 30%;">
                <a class="button" href="{% url 'users:update_name' %}">修改</a>
            </div>
        </div>
        <div>
            <div style="width: 70%;">
                <p><span style="font-weight: bold;">Email:</span> {{ CustomUser_info.email }}</p>
            </div>
            <div style="width: 30%;">
                <a class="button" href="{% url 'users:update_email' %}">修改</a>
            </div>
        </div>
        <div>
            <div style="width: 70%;">
                <p><span style="font-weight: bold;">Sno:</span> {{ CustomUser_info.Sno }}</p>
            </div>
            <div style="width: 30%;">
                <a class="button" href="{% url 'users:update_sno' %}">修改</a>
            </div>
        </div>
        <div>
            <div style="width: 70%;">
                <p><span style="font-weight: bold;">Phone:</span> {{ CustomUser_info.phone }}</p>
            </div>
            <div style="width: 30%;">
                <a class="button" href="{% url 'users:update_phone' %}">修改</a>
            </div>
        </div>
    </div>
{% endblock content %}
</body>
</html>

users/templates/update/update_name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Name</title>
        <style>
            .button{
        background-color: mediumpurple;
        text-decoration: none;
        color: white;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-left: 7px;
        padding-right: 7px;
        border-radius: 5px;
    }
    </style>
</head>
<body>
 {% extends "bbs/base.html" %}

    {% block content %}
    <h1>Update Name</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Update Name</button>
    </form>


    {% endblock %}
</body>
</html>

users/templates/update/update_phone.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Phone</title>
    <style>
            .button{
        background-color: mediumpurple;
        text-decoration: none;
        color: white;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-left: 7px;
        padding-right: 7px;
        border-radius: 5px;
    }
    </style>
</head>
<body>
    {% extends "bbs/base.html" %}

    {% block content %}

    <h1>Update Phone</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" type="submit">Update Phone</button>
    </form>

    {% endblock %}
</body>
</html>

users/templates/update/update_sno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Sno</title>
     <style>
            .button{
        background-color: mediumpurple;
        text-decoration: none;
        color: white;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-left: 7px;
        padding-right: 7px;
        border-radius: 5px;
    }
    </style>
</head>
<body>
 {% extends "bbs/base.html" %}

    {% block content %}
    <h1>Update Sno</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Update Sno</button>
    </form>

    <!-- 确保已引入 jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#send_code_btn").click(function () {
                var email = $("#id_email").val();
                $.ajax({
                    url: "{% url 'users:send_verification_code' %}",
                    type: "POST",
                    data: {
                        email: email,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        if (data.success) {
                            alert("验证码已发送到你的邮箱");
                        } else {
                            alert("错误: " + data.error);
                        }
                    }
                });
            });
        });
    </script>
    {% endblock %}
</body>
</html>